from PySide6.QtGui import QColor, QFont

__all__ = ('DEFAULT_COLORS', 'HOVER_ITEM_COLOR',
           'DARK_THEME_LIST_WIDGET_ITEM_DEFAULT_COLOR', 'DARK_THEME_LIST_WIDGET_ITEM_SELECTED_COLOR',
           'LIGHT_THEME_LIST_WIDGET_ITEM_DEFAULT_COLOR', 'LIGHT_THEME_LIST_WIDGET_ITEM_SELECTED_COLOR',
           'ERASER_CURSOR_PATH')

DEFAULT_COLORS = ('#000000', '#800000', '#400080', '#0004ff', '#8d8b9a', '#22b14c',
                  '#ff0000', '#ff00ea', '#ff80ff', '#ff8000', '#dcdc00', '#00ff00')

HOVER_ITEM_COLOR = QColor('#ffcb30')

DARK_THEME_LIST_WIDGET_ITEM_DEFAULT_COLOR = QColor('#b1b1b1')
DARK_THEME_LIST_WIDGET_ITEM_SELECTED_COLOR = QColor('#27c727')
LIGHT_THEME_LIST_WIDGET_ITEM_DEFAULT_COLOR = QColor('#000000')
LIGHT_THEME_LIST_WIDGET_ITEM_SELECTED_COLOR = QColor('#1a6aa7')

ERASER_CURSOR_PATH = '://cursors/cursors/eraser.cur'
