# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PlayCreator.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFontComboBox, QFormLayout,
    QGridLayout, QGroupBox, QHBoxLayout, QLabel,
    QLayout, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpacerItem, QStatusBar, QToolBar,
    QVBoxLayout, QWidget)
import Interface_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1425, 890)
        MainWindow.setMinimumSize(QSize(1425, 890))
        self.action_save_like_picture = QAction(MainWindow)
        self.action_save_like_picture.setObjectName(u"action_save_like_picture")
        self.action_save_like_picture.setEnabled(True)
        self.action_save_like_picture.setIconVisibleInMenu(False)
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        self.action_about.setIconVisibleInMenu(False)
        self.action_presentation_mode = QAction(MainWindow)
        self.action_presentation_mode.setObjectName(u"action_presentation_mode")
        self.action_presentation_mode.setCheckable(True)
        self.action_presentation_mode.setEnabled(True)
        self.action_presentation_mode.setIconVisibleInMenu(False)
        self.action_QB_Wrist = QAction(MainWindow)
        self.action_QB_Wrist.setObjectName(u"action_QB_Wrist")
        self.action_QB_Wrist.setEnabled(False)
        self.action_QB_Wrist.setIconVisibleInMenu(False)
        self.action_light_theme = QAction(MainWindow)
        self.action_light_theme.setObjectName(u"action_light_theme")
        self.action_light_theme.setCheckable(True)
        self.action_light_theme.setIconVisibleInMenu(False)
        self.action_dark_theme = QAction(MainWindow)
        self.action_dark_theme.setObjectName(u"action_dark_theme")
        self.action_dark_theme.setCheckable(True)
        self.action_dark_theme.setChecked(False)
        self.action_dark_theme.setIconVisibleInMenu(False)
        self.action_save_all_like_picture = QAction(MainWindow)
        self.action_save_all_like_picture.setObjectName(u"action_save_all_like_picture")
        self.action_save_all_like_picture.setEnabled(True)
        self.action_save_all_like_picture.setIconVisibleInMenu(False)
        self.action_save_playbook_local = QAction(MainWindow)
        self.action_save_playbook_local.setObjectName(u"action_save_playbook_local")
        self.action_save_playbook_local.setEnabled(True)
        self.action_save_playbook_local.setIconVisibleInMenu(False)
        self.action_new_playbook = QAction(MainWindow)
        self.action_new_playbook.setObjectName(u"action_new_playbook")
        self.action_new_playbook.setEnabled(True)
        self.action_new_playbook.setIconVisibleInMenu(False)
        self.action_user_login = QAction(MainWindow)
        self.action_user_login.setObjectName(u"action_user_login")
        self.action_user_login.setEnabled(True)
        self.action_user_login.setIconVisibleInMenu(False)
        self.action_user_logout = QAction(MainWindow)
        self.action_user_logout.setObjectName(u"action_user_logout")
        self.action_user_logout.setEnabled(True)
        self.action_user_logout.setIconVisibleInMenu(False)
        self.action_open_local_playbook = QAction(MainWindow)
        self.action_open_local_playbook.setObjectName(u"action_open_local_playbook")
        self.action_open_local_playbook.setEnabled(True)
        self.action_open_local_playbook.setIconVisibleInMenu(False)
        self.action_close_app = QAction(MainWindow)
        self.action_close_app.setObjectName(u"action_close_app")
        self.action_close_app.setIconVisibleInMenu(False)
        self.action_open_remote_playbook = QAction(MainWindow)
        self.action_open_remote_playbook.setObjectName(u"action_open_remote_playbook")
        self.action_open_remote_playbook.setEnabled(True)
        self.action_open_remote_playbook.setIconVisibleInMenu(False)
        self.action_toolbar_visible = QAction(MainWindow)
        self.action_toolbar_visible.setObjectName(u"action_toolbar_visible")
        self.action_toolbar_visible.setCheckable(True)
        self.action_toolbar_visible.setChecked(True)
        self.action_save_playbook_local_as = QAction(MainWindow)
        self.action_save_playbook_local_as.setObjectName(u"action_save_playbook_local_as")
        self.action_save_playbook_local_as.setEnabled(True)
        self.action_save_playbook_local_as.setIconVisibleInMenu(False)
        self.action_show_remove_scheme_dialog = QAction(MainWindow)
        self.action_show_remove_scheme_dialog.setObjectName(u"action_show_remove_scheme_dialog")
        self.action_show_remove_scheme_dialog.setCheckable(True)
        self.action_show_remove_scheme_dialog.setChecked(True)
        self.action_show_close_app_dialog = QAction(MainWindow)
        self.action_show_close_app_dialog.setObjectName(u"action_show_close_app_dialog")
        self.action_show_close_app_dialog.setCheckable(True)
        self.action_show_close_app_dialog.setChecked(True)
        self.action_redo = QAction(MainWindow)
        self.action_redo.setObjectName(u"action_redo")
        self.action_undo = QAction(MainWindow)
        self.action_undo.setObjectName(u"action_undo")
        self.action_save_to_remote_server_as = QAction(MainWindow)
        self.action_save_to_remote_server_as.setObjectName(u"action_save_to_remote_server_as")
        self.action_save_to_remote_server = QAction(MainWindow)
        self.action_save_to_remote_server.setObjectName(u"action_save_to_remote_server")
        self.action_save_to_remote_server.setEnabled(True)
        self.action_save_to_remote_server.setIconVisibleInMenu(False)
        self.action_show_save_changed_playbook_dialog = QAction(MainWindow)
        self.action_show_save_changed_playbook_dialog.setObjectName(u"action_show_save_changed_playbook_dialog")
        self.action_show_save_changed_playbook_dialog.setCheckable(True)
        self.action_show_save_changed_playbook_dialog.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_6 = QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.groupBox_team_playbook_settings = QGroupBox(self.centralwidget)
        self.groupBox_team_playbook_settings.setObjectName(u"groupBox_team_playbook_settings")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_team_playbook_settings.sizePolicy().hasHeightForWidth())
        self.groupBox_team_playbook_settings.setSizePolicy(sizePolicy)
        self.groupBox_team_playbook_settings.setMinimumSize(QSize(358, 500))
        self.groupBox_team_playbook_settings.setMaximumSize(QSize(358, 6000))
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_team_playbook_settings)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.widget_teams_management = QWidget(self.groupBox_team_playbook_settings)
        self.widget_teams_management.setObjectName(u"widget_teams_management")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget_teams_management.sizePolicy().hasHeightForWidth())
        self.widget_teams_management.setSizePolicy(sizePolicy1)
        self.widget_teams_management.setMinimumSize(QSize(336, 0))
        self.widget_teams_management.setMaximumSize(QSize(336, 16777215))
        self.verticalLayout = QVBoxLayout(self.widget_teams_management)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_place_team_and_yards = QHBoxLayout()
        self.horizontalLayout_place_team_and_yards.setObjectName(u"horizontalLayout_place_team_and_yards")
        self.verticalLayout_team_type = QVBoxLayout()
        self.verticalLayout_team_type.setObjectName(u"verticalLayout_team_type")
        self.label_place_players = QLabel(self.widget_teams_management)
        self.label_place_players.setObjectName(u"label_place_players")
        self.label_place_players.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.label_place_players.sizePolicy().hasHeightForWidth())
        self.label_place_players.setSizePolicy(sizePolicy1)
        self.label_place_players.setMinimumSize(QSize(165, 25))
        self.label_place_players.setMaximumSize(QSize(1500, 25))
        font = QFont()
        font.setPointSize(10)
        self.label_place_players.setFont(font)

        self.verticalLayout_team_type.addWidget(self.label_place_players)

        self.comboBox_team_type = QComboBox(self.widget_teams_management)
        self.comboBox_team_type.addItem("")
        self.comboBox_team_type.addItem("")
        self.comboBox_team_type.addItem("")
        self.comboBox_team_type.addItem("")
        self.comboBox_team_type.setObjectName(u"comboBox_team_type")
        self.comboBox_team_type.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.comboBox_team_type.sizePolicy().hasHeightForWidth())
        self.comboBox_team_type.setSizePolicy(sizePolicy1)
        self.comboBox_team_type.setMinimumSize(QSize(165, 25))
        self.comboBox_team_type.setMaximumSize(QSize(1500, 25))
        self.comboBox_team_type.setFont(font)
        self.comboBox_team_type.setFocusPolicy(Qt.ClickFocus)

        self.verticalLayout_team_type.addWidget(self.comboBox_team_type)


        self.horizontalLayout_place_team_and_yards.addLayout(self.verticalLayout_team_type)

        self.verticalLayout_yards = QVBoxLayout()
        self.verticalLayout_yards.setObjectName(u"verticalLayout_yards")
        self.label_yards = QLabel(self.widget_teams_management)
        self.label_yards.setObjectName(u"label_yards")
        sizePolicy1.setHeightForWidth(self.label_yards.sizePolicy().hasHeightForWidth())
        self.label_yards.setSizePolicy(sizePolicy1)
        self.label_yards.setMinimumSize(QSize(165, 25))
        self.label_yards.setMaximumSize(QSize(1500, 25))
        self.label_yards.setFont(font)

        self.verticalLayout_yards.addWidget(self.label_yards)

        self.lineEdit_yards = QLineEdit(self.widget_teams_management)
        self.lineEdit_yards.setObjectName(u"lineEdit_yards")
        self.lineEdit_yards.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.lineEdit_yards.sizePolicy().hasHeightForWidth())
        self.lineEdit_yards.setSizePolicy(sizePolicy2)
        self.lineEdit_yards.setMinimumSize(QSize(165, 25))
        self.lineEdit_yards.setMaximumSize(QSize(1500, 25))
        self.lineEdit_yards.setFont(font)
        self.lineEdit_yards.setFocusPolicy(Qt.ClickFocus)
        self.lineEdit_yards.setMaxLength(3)

        self.verticalLayout_yards.addWidget(self.lineEdit_yards)


        self.horizontalLayout_place_team_and_yards.addLayout(self.verticalLayout_yards)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_place_team_and_yards.addItem(self.horizontalSpacer_2)


        self.verticalLayout.addLayout(self.horizontalLayout_place_team_and_yards)

        self.gridLayout_team_buttons = QGridLayout()
        self.gridLayout_team_buttons.setObjectName(u"gridLayout_team_buttons")
        self.pushButton_place_second_team = QPushButton(self.widget_teams_management)
        self.pushButton_place_second_team.setObjectName(u"pushButton_place_second_team")
        self.pushButton_place_second_team.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_place_second_team.sizePolicy().hasHeightForWidth())
        self.pushButton_place_second_team.setSizePolicy(sizePolicy1)
        self.pushButton_place_second_team.setMinimumSize(QSize(165, 25))
        self.pushButton_place_second_team.setMaximumSize(QSize(1500, 25))
        self.pushButton_place_second_team.setFont(font)
        self.pushButton_place_second_team.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_team_buttons.addWidget(self.pushButton_place_second_team, 1, 0, 1, 1)

        self.pushButton_place_first_team = QPushButton(self.widget_teams_management)
        self.pushButton_place_first_team.setObjectName(u"pushButton_place_first_team")
        self.pushButton_place_first_team.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_place_first_team.sizePolicy().hasHeightForWidth())
        self.pushButton_place_first_team.setSizePolicy(sizePolicy1)
        self.pushButton_place_first_team.setMinimumSize(QSize(165, 25))
        self.pushButton_place_first_team.setMaximumSize(QSize(1500, 25))
        self.pushButton_place_first_team.setFont(font)
        self.pushButton_place_first_team.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_team_buttons.addWidget(self.pushButton_place_first_team, 0, 0, 1, 1)

        self.pushButton_remove_second_team = QPushButton(self.widget_teams_management)
        self.pushButton_remove_second_team.setObjectName(u"pushButton_remove_second_team")
        self.pushButton_remove_second_team.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_second_team.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_second_team.setSizePolicy(sizePolicy1)
        self.pushButton_remove_second_team.setMinimumSize(QSize(165, 25))
        self.pushButton_remove_second_team.setMaximumSize(QSize(1500, 25))
        self.pushButton_remove_second_team.setFont(font)
        self.pushButton_remove_second_team.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_team_buttons.addWidget(self.pushButton_remove_second_team, 2, 0, 1, 1)

        self.horizontalLayout_additional_player_buttons = QHBoxLayout()
        self.horizontalLayout_additional_player_buttons.setObjectName(u"horizontalLayout_additional_player_buttons")
        self.pushButton_add_additional_off_player = QPushButton(self.widget_teams_management)
        self.pushButton_add_additional_off_player.setObjectName(u"pushButton_add_additional_off_player")
        self.pushButton_add_additional_off_player.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_add_additional_off_player.sizePolicy().hasHeightForWidth())
        self.pushButton_add_additional_off_player.setSizePolicy(sizePolicy1)
        self.pushButton_add_additional_off_player.setMinimumSize(QSize(30, 25))
        self.pushButton_add_additional_off_player.setMaximumSize(QSize(30, 25))
        self.pushButton_add_additional_off_player.setFont(font)
        self.pushButton_add_additional_off_player.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_additional_player_buttons.addWidget(self.pushButton_add_additional_off_player)

        self.pushButton_del_additional_off_player = QPushButton(self.widget_teams_management)
        self.pushButton_del_additional_off_player.setObjectName(u"pushButton_del_additional_off_player")
        self.pushButton_del_additional_off_player.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_del_additional_off_player.sizePolicy().hasHeightForWidth())
        self.pushButton_del_additional_off_player.setSizePolicy(sizePolicy1)
        self.pushButton_del_additional_off_player.setMinimumSize(QSize(30, 25))
        self.pushButton_del_additional_off_player.setMaximumSize(QSize(30, 25))
        self.pushButton_del_additional_off_player.setFont(font)
        self.pushButton_del_additional_off_player.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_additional_player_buttons.addWidget(self.pushButton_del_additional_off_player)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_additional_player_buttons.addItem(self.horizontalSpacer_6)


        self.gridLayout_team_buttons.addLayout(self.horizontalLayout_additional_player_buttons, 0, 1, 1, 1)

        self.comboBox_second_players_symbol = QComboBox(self.widget_teams_management)
        self.comboBox_second_players_symbol.addItem("")
        self.comboBox_second_players_symbol.addItem("")
        self.comboBox_second_players_symbol.addItem("")
        self.comboBox_second_players_symbol.addItem("")
        self.comboBox_second_players_symbol.setObjectName(u"comboBox_second_players_symbol")
        self.comboBox_second_players_symbol.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.comboBox_second_players_symbol.sizePolicy().hasHeightForWidth())
        self.comboBox_second_players_symbol.setSizePolicy(sizePolicy1)
        self.comboBox_second_players_symbol.setMinimumSize(QSize(66, 25))
        self.comboBox_second_players_symbol.setMaximumSize(QSize(66, 25))
        self.comboBox_second_players_symbol.setFocusPolicy(Qt.ClickFocus)
        self.comboBox_second_players_symbol.setEditable(False)

        self.gridLayout_team_buttons.addWidget(self.comboBox_second_players_symbol, 1, 1, 1, 1)

        self.pushButton_remove_all_players = QPushButton(self.widget_teams_management)
        self.pushButton_remove_all_players.setObjectName(u"pushButton_remove_all_players")
        self.pushButton_remove_all_players.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_all_players.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_all_players.setSizePolicy(sizePolicy1)
        self.pushButton_remove_all_players.setMinimumSize(QSize(165, 25))
        self.pushButton_remove_all_players.setMaximumSize(QSize(1500, 25))
        self.pushButton_remove_all_players.setFont(font)
        self.pushButton_remove_all_players.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_team_buttons.addWidget(self.pushButton_remove_all_players, 2, 1, 1, 1)


        self.verticalLayout.addLayout(self.gridLayout_team_buttons)


        self.verticalLayout_2.addWidget(self.widget_teams_management)

        self.widget_playbook = QWidget(self.groupBox_team_playbook_settings)
        self.widget_playbook.setObjectName(u"widget_playbook")
        sizePolicy.setHeightForWidth(self.widget_playbook.sizePolicy().hasHeightForWidth())
        self.widget_playbook.setSizePolicy(sizePolicy)
        self.widget_playbook.setMinimumSize(QSize(336, 0))
        self.widget_playbook.setMaximumSize(QSize(336, 10000))
        self.gridLayout_2 = QGridLayout(self.widget_playbook)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_playbook = QHBoxLayout()
        self.horizontalLayout_playbook.setObjectName(u"horizontalLayout_playbook")
        self.label_playbook_name = QLabel(self.widget_playbook)
        self.label_playbook_name.setObjectName(u"label_playbook_name")
        self.label_playbook_name.setMinimumSize(QSize(180, 30))
        self.label_playbook_name.setMaximumSize(QSize(10000, 30))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(14)
        font1.setBold(True)
        self.label_playbook_name.setFont(font1)
        self.label_playbook_name.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_playbook.addWidget(self.label_playbook_name)

        self.pushButton_edit_playbook = QPushButton(self.widget_playbook)
        self.pushButton_edit_playbook.setObjectName(u"pushButton_edit_playbook")
        self.pushButton_edit_playbook.setEnabled(True)
        self.pushButton_edit_playbook.setMinimumSize(QSize(25, 25))
        self.pushButton_edit_playbook.setMaximumSize(QSize(25, 25))
        self.pushButton_edit_playbook.setFocusPolicy(Qt.ClickFocus)

        self.horizontalLayout_playbook.addWidget(self.pushButton_edit_playbook)


        self.gridLayout_2.addLayout(self.horizontalLayout_playbook, 0, 0, 1, 2)

        self.listWidget_schemes = QListWidget(self.widget_playbook)
        self.listWidget_schemes.setObjectName(u"listWidget_schemes")
        self.listWidget_schemes.setEnabled(True)
        self.listWidget_schemes.setMinimumSize(QSize(336, 250))
        self.listWidget_schemes.setMaximumSize(QSize(336, 100000))
        font2 = QFont()
        font2.setFamilies([u"Times New Roman"])
        font2.setPointSize(15)
        self.listWidget_schemes.setFont(font2)
        self.listWidget_schemes.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.listWidget_schemes, 1, 0, 1, 2)

        self.pushButton_edit_scheme = QPushButton(self.widget_playbook)
        self.pushButton_edit_scheme.setObjectName(u"pushButton_edit_scheme")
        self.pushButton_edit_scheme.setEnabled(True)
        self.pushButton_edit_scheme.setMinimumSize(QSize(336, 25))
        self.pushButton_edit_scheme.setMaximumSize(QSize(336, 25))
        self.pushButton_edit_scheme.setFont(font)
        self.pushButton_edit_scheme.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.pushButton_edit_scheme, 2, 0, 1, 2)

        self.pushButton_add_scheme = QPushButton(self.widget_playbook)
        self.pushButton_add_scheme.setObjectName(u"pushButton_add_scheme")
        self.pushButton_add_scheme.setEnabled(True)
        self.pushButton_add_scheme.setMinimumSize(QSize(165, 25))
        self.pushButton_add_scheme.setMaximumSize(QSize(165, 25))
        self.pushButton_add_scheme.setFont(font)
        self.pushButton_add_scheme.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.pushButton_add_scheme, 3, 0, 1, 1)

        self.pushButton_move_up_scheme = QPushButton(self.widget_playbook)
        self.pushButton_move_up_scheme.setObjectName(u"pushButton_move_up_scheme")
        self.pushButton_move_up_scheme.setEnabled(True)
        self.pushButton_move_up_scheme.setMinimumSize(QSize(165, 25))
        self.pushButton_move_up_scheme.setMaximumSize(QSize(165, 25))
        self.pushButton_move_up_scheme.setFont(font)
        self.pushButton_move_up_scheme.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.pushButton_move_up_scheme, 4, 0, 1, 1)

        self.pushButton_move_down_scheme = QPushButton(self.widget_playbook)
        self.pushButton_move_down_scheme.setObjectName(u"pushButton_move_down_scheme")
        self.pushButton_move_down_scheme.setEnabled(True)
        self.pushButton_move_down_scheme.setMinimumSize(QSize(165, 25))
        self.pushButton_move_down_scheme.setMaximumSize(QSize(165, 25))
        self.pushButton_move_down_scheme.setFont(font)
        self.pushButton_move_down_scheme.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.pushButton_move_down_scheme, 4, 1, 1, 1)

        self.pushButton_remove_scheme = QPushButton(self.widget_playbook)
        self.pushButton_remove_scheme.setObjectName(u"pushButton_remove_scheme")
        self.pushButton_remove_scheme.setEnabled(True)
        self.pushButton_remove_scheme.setMinimumSize(QSize(165, 25))
        self.pushButton_remove_scheme.setMaximumSize(QSize(165, 25))
        self.pushButton_remove_scheme.setFont(font)
        self.pushButton_remove_scheme.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_2.addWidget(self.pushButton_remove_scheme, 3, 1, 1, 1)


        self.verticalLayout_2.addWidget(self.widget_playbook)


        self.gridLayout_6.addWidget(self.groupBox_team_playbook_settings, 1, 1, 1, 1)

        self.widget_painting_tools = QWidget(self.centralwidget)
        self.widget_painting_tools.setObjectName(u"widget_painting_tools")
        self.formLayout = QFormLayout(self.widget_painting_tools)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setRowWrapPolicy(QFormLayout.WrapLongRows)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_painting_2 = QHBoxLayout()
        self.horizontalLayout_painting_2.setSpacing(6)
        self.horizontalLayout_painting_2.setObjectName(u"horizontalLayout_painting_2")
        self.horizontalLayout_painting_2.setSizeConstraint(QLayout.SetFixedSize)
        self.horizontalLayout_painting_2.setContentsMargins(-1, -1, 6, -1)
        self.groupBox_move_erase = QGroupBox(self.widget_painting_tools)
        self.groupBox_move_erase.setObjectName(u"groupBox_move_erase")
        self.groupBox_move_erase.setEnabled(True)
        self.groupBox_move_erase.setMinimumSize(QSize(111, 61))
        self.groupBox_move_erase.setMaximumSize(QSize(111, 61))
        self.groupBox_move_erase.setCheckable(False)
        self.gridLayout = QGridLayout(self.groupBox_move_erase)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pushButton_move = QPushButton(self.groupBox_move_erase)
        self.pushButton_move.setObjectName(u"pushButton_move")
        self.pushButton_move.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_move.sizePolicy().hasHeightForWidth())
        self.pushButton_move.setSizePolicy(sizePolicy1)
        self.pushButton_move.setMinimumSize(QSize(40, 40))
        self.pushButton_move.setMaximumSize(QSize(40, 40))
        self.pushButton_move.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_move.setIconSize(QSize(35, 35))
        self.pushButton_move.setCheckable(True)
        self.pushButton_move.setChecked(True)

        self.gridLayout.addWidget(self.pushButton_move, 0, 0, 1, 1)

        self.pushButton_erase = QPushButton(self.groupBox_move_erase)
        self.pushButton_erase.setObjectName(u"pushButton_erase")
        self.pushButton_erase.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_erase.sizePolicy().hasHeightForWidth())
        self.pushButton_erase.setSizePolicy(sizePolicy1)
        self.pushButton_erase.setMinimumSize(QSize(40, 40))
        self.pushButton_erase.setMaximumSize(QSize(40, 40))
        self.pushButton_erase.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_erase.setIconSize(QSize(35, 35))
        self.pushButton_erase.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_erase, 0, 1, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_move_erase)

        self.groupBox_colors = QGroupBox(self.widget_painting_tools)
        self.groupBox_colors.setObjectName(u"groupBox_colors")
        self.groupBox_colors.setEnabled(True)
        self.groupBox_colors.setMinimumSize(QSize(191, 61))
        self.groupBox_colors.setMaximumSize(QSize(191, 61))
        self.gridLayout_3 = QGridLayout(self.groupBox_colors)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.pushButton_color_current = QPushButton(self.groupBox_colors)
        self.pushButton_color_current.setObjectName(u"pushButton_color_current")
        self.pushButton_color_current.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_current.sizePolicy().hasHeightForWidth())
        self.pushButton_color_current.setSizePolicy(sizePolicy1)
        self.pushButton_color_current.setMinimumSize(QSize(40, 40))
        self.pushButton_color_current.setMaximumSize(QSize(40, 40))
        self.pushButton_color_current.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_3.addWidget(self.pushButton_color_current, 0, 0, 1, 1)

        self.gridLayout_colors = QGridLayout()
        self.gridLayout_colors.setObjectName(u"gridLayout_colors")
        self.gridLayout_colors.setHorizontalSpacing(2)
        self.gridLayout_colors.setVerticalSpacing(4)
        self.pushButton_color_10 = QPushButton(self.groupBox_colors)
        self.pushButton_color_10.setObjectName(u"pushButton_color_10")
        self.pushButton_color_10.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_10.sizePolicy().hasHeightForWidth())
        self.pushButton_color_10.setSizePolicy(sizePolicy1)
        self.pushButton_color_10.setMinimumSize(QSize(18, 18))
        self.pushButton_color_10.setMaximumSize(QSize(18, 18))
        self.pushButton_color_10.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_10, 1, 4, 1, 1)

        self.pushButton_color_9 = QPushButton(self.groupBox_colors)
        self.pushButton_color_9.setObjectName(u"pushButton_color_9")
        self.pushButton_color_9.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_9.sizePolicy().hasHeightForWidth())
        self.pushButton_color_9.setSizePolicy(sizePolicy1)
        self.pushButton_color_9.setMinimumSize(QSize(18, 18))
        self.pushButton_color_9.setMaximumSize(QSize(18, 18))
        self.pushButton_color_9.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_9, 1, 3, 1, 1)

        self.pushButton_color_4 = QPushButton(self.groupBox_colors)
        self.pushButton_color_4.setObjectName(u"pushButton_color_4")
        self.pushButton_color_4.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_4.sizePolicy().hasHeightForWidth())
        self.pushButton_color_4.setSizePolicy(sizePolicy1)
        self.pushButton_color_4.setMinimumSize(QSize(18, 18))
        self.pushButton_color_4.setMaximumSize(QSize(18, 18))
        self.pushButton_color_4.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_4, 0, 4, 1, 1)

        self.pushButton_color_6 = QPushButton(self.groupBox_colors)
        self.pushButton_color_6.setObjectName(u"pushButton_color_6")
        self.pushButton_color_6.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_6.sizePolicy().hasHeightForWidth())
        self.pushButton_color_6.setSizePolicy(sizePolicy1)
        self.pushButton_color_6.setMinimumSize(QSize(18, 18))
        self.pushButton_color_6.setMaximumSize(QSize(18, 18))
        self.pushButton_color_6.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_6, 1, 0, 1, 1)

        self.pushButton_color_7 = QPushButton(self.groupBox_colors)
        self.pushButton_color_7.setObjectName(u"pushButton_color_7")
        self.pushButton_color_7.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_7.sizePolicy().hasHeightForWidth())
        self.pushButton_color_7.setSizePolicy(sizePolicy1)
        self.pushButton_color_7.setMinimumSize(QSize(18, 18))
        self.pushButton_color_7.setMaximumSize(QSize(18, 18))
        self.pushButton_color_7.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_7, 1, 1, 1, 1)

        self.pushButton_color_1 = QPushButton(self.groupBox_colors)
        self.pushButton_color_1.setObjectName(u"pushButton_color_1")
        self.pushButton_color_1.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_1.sizePolicy().hasHeightForWidth())
        self.pushButton_color_1.setSizePolicy(sizePolicy1)
        self.pushButton_color_1.setMinimumSize(QSize(18, 18))
        self.pushButton_color_1.setMaximumSize(QSize(18, 18))
        self.pushButton_color_1.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_1, 0, 1, 1, 1)

        self.pushButton_color_8 = QPushButton(self.groupBox_colors)
        self.pushButton_color_8.setObjectName(u"pushButton_color_8")
        self.pushButton_color_8.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_8.sizePolicy().hasHeightForWidth())
        self.pushButton_color_8.setSizePolicy(sizePolicy1)
        self.pushButton_color_8.setMinimumSize(QSize(18, 18))
        self.pushButton_color_8.setMaximumSize(QSize(18, 18))
        self.pushButton_color_8.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_8, 1, 2, 1, 1)

        self.pushButton_color_2 = QPushButton(self.groupBox_colors)
        self.pushButton_color_2.setObjectName(u"pushButton_color_2")
        self.pushButton_color_2.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_2.sizePolicy().hasHeightForWidth())
        self.pushButton_color_2.setSizePolicy(sizePolicy1)
        self.pushButton_color_2.setMinimumSize(QSize(18, 18))
        self.pushButton_color_2.setMaximumSize(QSize(18, 18))
        self.pushButton_color_2.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_2, 0, 2, 1, 1)

        self.pushButton_color_3 = QPushButton(self.groupBox_colors)
        self.pushButton_color_3.setObjectName(u"pushButton_color_3")
        self.pushButton_color_3.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_3.sizePolicy().hasHeightForWidth())
        self.pushButton_color_3.setSizePolicy(sizePolicy1)
        self.pushButton_color_3.setMinimumSize(QSize(18, 18))
        self.pushButton_color_3.setMaximumSize(QSize(18, 18))
        self.pushButton_color_3.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_3, 0, 3, 1, 1)

        self.pushButton_color_0 = QPushButton(self.groupBox_colors)
        self.pushButton_color_0.setObjectName(u"pushButton_color_0")
        self.pushButton_color_0.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_0.sizePolicy().hasHeightForWidth())
        self.pushButton_color_0.setSizePolicy(sizePolicy1)
        self.pushButton_color_0.setMinimumSize(QSize(18, 18))
        self.pushButton_color_0.setMaximumSize(QSize(18, 18))
        self.pushButton_color_0.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_0, 0, 0, 1, 1)

        self.pushButton_color_5 = QPushButton(self.groupBox_colors)
        self.pushButton_color_5.setObjectName(u"pushButton_color_5")
        self.pushButton_color_5.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_5.sizePolicy().hasHeightForWidth())
        self.pushButton_color_5.setSizePolicy(sizePolicy1)
        self.pushButton_color_5.setMinimumSize(QSize(18, 18))
        self.pushButton_color_5.setMaximumSize(QSize(18, 18))
        self.pushButton_color_5.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_5, 0, 5, 1, 1)

        self.pushButton_color_11 = QPushButton(self.groupBox_colors)
        self.pushButton_color_11.setObjectName(u"pushButton_color_11")
        self.pushButton_color_11.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_color_11.sizePolicy().hasHeightForWidth())
        self.pushButton_color_11.setSizePolicy(sizePolicy1)
        self.pushButton_color_11.setMinimumSize(QSize(18, 18))
        self.pushButton_color_11.setMaximumSize(QSize(18, 18))
        self.pushButton_color_11.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_colors.addWidget(self.pushButton_color_11, 1, 5, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_colors, 0, 1, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_colors)

        self.groupBox_painting = QGroupBox(self.widget_painting_tools)
        self.groupBox_painting.setObjectName(u"groupBox_painting")
        self.groupBox_painting.setEnabled(True)
        self.groupBox_painting.setMinimumSize(QSize(475, 61))
        self.groupBox_painting.setMaximumSize(QSize(471, 61))
        self.gridLayout_4 = QGridLayout(self.groupBox_painting)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.pushButton_remove_actions = QPushButton(self.groupBox_painting)
        self.pushButton_remove_actions.setObjectName(u"pushButton_remove_actions")
        self.pushButton_remove_actions.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_actions.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_actions.setSizePolicy(sizePolicy1)
        self.pushButton_remove_actions.setMinimumSize(QSize(40, 40))
        self.pushButton_remove_actions.setMaximumSize(QSize(40, 40))
        self.pushButton_remove_actions.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_remove_actions.setIconSize(QSize(35, 35))

        self.gridLayout_4.addWidget(self.pushButton_remove_actions, 0, 4, 1, 1)

        self.pushButton_route = QPushButton(self.groupBox_painting)
        self.pushButton_route.setObjectName(u"pushButton_route")
        self.pushButton_route.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_route.sizePolicy().hasHeightForWidth())
        self.pushButton_route.setSizePolicy(sizePolicy1)
        self.pushButton_route.setMinimumSize(QSize(40, 40))
        self.pushButton_route.setMaximumSize(QSize(40, 40))
        self.pushButton_route.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_route.setIconSize(QSize(35, 35))
        self.pushButton_route.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_route, 0, 1, 1, 1)

        self.pushButton_block = QPushButton(self.groupBox_painting)
        self.pushButton_block.setObjectName(u"pushButton_block")
        self.pushButton_block.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_block.sizePolicy().hasHeightForWidth())
        self.pushButton_block.setSizePolicy(sizePolicy1)
        self.pushButton_block.setMinimumSize(QSize(40, 40))
        self.pushButton_block.setMaximumSize(QSize(40, 40))
        self.pushButton_block.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_block.setIconSize(QSize(35, 35))
        self.pushButton_block.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_block, 0, 2, 1, 1)

        self.pushButton_motion = QPushButton(self.groupBox_painting)
        self.pushButton_motion.setObjectName(u"pushButton_motion")
        self.pushButton_motion.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_motion.sizePolicy().hasHeightForWidth())
        self.pushButton_motion.setSizePolicy(sizePolicy1)
        self.pushButton_motion.setMinimumSize(QSize(40, 40))
        self.pushButton_motion.setMaximumSize(QSize(40, 40))
        self.pushButton_motion.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_motion.setIconSize(QSize(35, 35))
        self.pushButton_motion.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_motion, 0, 3, 1, 1)

        self.pushButton_remove_pencil = QPushButton(self.groupBox_painting)
        self.pushButton_remove_pencil.setObjectName(u"pushButton_remove_pencil")
        self.pushButton_remove_pencil.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_pencil.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_pencil.setSizePolicy(sizePolicy1)
        self.pushButton_remove_pencil.setMinimumSize(QSize(40, 40))
        self.pushButton_remove_pencil.setMaximumSize(QSize(40, 40))
        self.pushButton_remove_pencil.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_remove_pencil.setIconSize(QSize(35, 35))
        self.pushButton_remove_pencil.setCheckable(False)

        self.gridLayout_4.addWidget(self.pushButton_remove_pencil, 0, 9, 1, 1)

        self.pushButton_rectangle = QPushButton(self.groupBox_painting)
        self.pushButton_rectangle.setObjectName(u"pushButton_rectangle")
        self.pushButton_rectangle.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_rectangle.sizePolicy().hasHeightForWidth())
        self.pushButton_rectangle.setSizePolicy(sizePolicy1)
        self.pushButton_rectangle.setMinimumSize(QSize(40, 40))
        self.pushButton_rectangle.setMaximumSize(QSize(40, 40))
        self.pushButton_rectangle.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_rectangle.setIconSize(QSize(35, 35))
        self.pushButton_rectangle.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_rectangle, 0, 5, 1, 1)

        self.pushButton_remove_figures = QPushButton(self.groupBox_painting)
        self.pushButton_remove_figures.setObjectName(u"pushButton_remove_figures")
        self.pushButton_remove_figures.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_figures.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_figures.setSizePolicy(sizePolicy1)
        self.pushButton_remove_figures.setMinimumSize(QSize(40, 40))
        self.pushButton_remove_figures.setMaximumSize(QSize(40, 40))
        self.pushButton_remove_figures.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_remove_figures.setIconSize(QSize(35, 35))
        self.pushButton_remove_figures.setCheckable(False)

        self.gridLayout_4.addWidget(self.pushButton_remove_figures, 0, 7, 1, 1)

        self.pushButton_ellipse = QPushButton(self.groupBox_painting)
        self.pushButton_ellipse.setObjectName(u"pushButton_ellipse")
        self.pushButton_ellipse.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_ellipse.sizePolicy().hasHeightForWidth())
        self.pushButton_ellipse.setSizePolicy(sizePolicy1)
        self.pushButton_ellipse.setMinimumSize(QSize(40, 40))
        self.pushButton_ellipse.setMaximumSize(QSize(40, 40))
        self.pushButton_ellipse.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_ellipse.setIconSize(QSize(35, 35))
        self.pushButton_ellipse.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_ellipse, 0, 6, 1, 1)

        self.pushButton_pencil = QPushButton(self.groupBox_painting)
        self.pushButton_pencil.setObjectName(u"pushButton_pencil")
        self.pushButton_pencil.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_pencil.sizePolicy().hasHeightForWidth())
        self.pushButton_pencil.setSizePolicy(sizePolicy1)
        self.pushButton_pencil.setMinimumSize(QSize(40, 40))
        self.pushButton_pencil.setMaximumSize(QSize(40, 40))
        self.pushButton_pencil.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_pencil.setIconSize(QSize(35, 35))
        self.pushButton_pencil.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_pencil, 0, 8, 1, 1)

        self.comboBox_line_thickness = QComboBox(self.groupBox_painting)
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.setObjectName(u"comboBox_line_thickness")
        self.comboBox_line_thickness.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.comboBox_line_thickness.sizePolicy().hasHeightForWidth())
        self.comboBox_line_thickness.setSizePolicy(sizePolicy1)
        self.comboBox_line_thickness.setMinimumSize(QSize(40, 25))
        self.comboBox_line_thickness.setMaximumSize(QSize(40, 25))
        self.comboBox_line_thickness.setFont(font)
        self.comboBox_line_thickness.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_4.addWidget(self.comboBox_line_thickness, 0, 0, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_painting)


        self.formLayout.setLayout(0, QFormLayout.LabelRole, self.horizontalLayout_painting_2)

        self.groupBox_label = QGroupBox(self.widget_painting_tools)
        self.groupBox_label.setObjectName(u"groupBox_label")
        self.groupBox_label.setEnabled(True)
        self.groupBox_label.setMinimumSize(QSize(501, 61))
        self.groupBox_label.setMaximumSize(QSize(501, 61))
        self.gridLayout_5 = QGridLayout(self.groupBox_label)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.pushButton_label = QPushButton(self.groupBox_label)
        self.pushButton_label.setObjectName(u"pushButton_label")
        self.pushButton_label.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_label.sizePolicy().hasHeightForWidth())
        self.pushButton_label.setSizePolicy(sizePolicy1)
        self.pushButton_label.setMinimumSize(QSize(40, 40))
        self.pushButton_label.setMaximumSize(QSize(40, 40))
        self.pushButton_label.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_label.setIconSize(QSize(35, 35))
        self.pushButton_label.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_label, 0, 0, 1, 1)

        self.pushButton_remove_labels = QPushButton(self.groupBox_label)
        self.pushButton_remove_labels.setObjectName(u"pushButton_remove_labels")
        self.pushButton_remove_labels.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_remove_labels.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_labels.setSizePolicy(sizePolicy1)
        self.pushButton_remove_labels.setMinimumSize(QSize(40, 40))
        self.pushButton_remove_labels.setMaximumSize(QSize(40, 40))
        self.pushButton_remove_labels.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_remove_labels.setIconSize(QSize(35, 35))
        self.pushButton_remove_labels.setCheckable(False)

        self.gridLayout_5.addWidget(self.pushButton_remove_labels, 0, 1, 1, 1)

        self.comboBox_font_type = QFontComboBox(self.groupBox_label)
        self.comboBox_font_type.setObjectName(u"comboBox_font_type")
        self.comboBox_font_type.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.comboBox_font_type.sizePolicy().hasHeightForWidth())
        self.comboBox_font_type.setSizePolicy(sizePolicy1)
        self.comboBox_font_type.setMinimumSize(QSize(225, 25))
        self.comboBox_font_type.setMaximumSize(QSize(225, 25))
        self.comboBox_font_type.setFont(font)
        self.comboBox_font_type.setFocusPolicy(Qt.ClickFocus)
        self.comboBox_font_type.setEditable(False)
        self.comboBox_font_type.setCurrentIndex(110)
        self.comboBox_font_type.setFontFilters(QFontComboBox.ScalableFonts)
        font3 = QFont()
        font3.setFamilies([u"Times New Roman"])
        self.comboBox_font_type.setCurrentFont(font3)

        self.gridLayout_5.addWidget(self.comboBox_font_type, 0, 2, 1, 1)

        self.comboBox_font_size = QComboBox(self.groupBox_label)
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.setObjectName(u"comboBox_font_size")
        self.comboBox_font_size.setEnabled(True)
        self.comboBox_font_size.setMinimumSize(QSize(45, 25))
        self.comboBox_font_size.setMaximumSize(QSize(45, 25))
        self.comboBox_font_size.setFont(font)
        self.comboBox_font_size.setFocusPolicy(Qt.ClickFocus)

        self.gridLayout_5.addWidget(self.comboBox_font_size, 0, 3, 1, 1)

        self.pushButton_font_bold = QPushButton(self.groupBox_label)
        self.pushButton_font_bold.setObjectName(u"pushButton_font_bold")
        self.pushButton_font_bold.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_font_bold.sizePolicy().hasHeightForWidth())
        self.pushButton_font_bold.setSizePolicy(sizePolicy1)
        self.pushButton_font_bold.setMinimumSize(QSize(30, 25))
        self.pushButton_font_bold.setMaximumSize(QSize(30, 25))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        self.pushButton_font_bold.setFont(font4)
        self.pushButton_font_bold.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_font_bold.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_font_bold, 0, 4, 1, 1)

        self.pushButton_font_italic = QPushButton(self.groupBox_label)
        self.pushButton_font_italic.setObjectName(u"pushButton_font_italic")
        self.pushButton_font_italic.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_font_italic.sizePolicy().hasHeightForWidth())
        self.pushButton_font_italic.setSizePolicy(sizePolicy1)
        self.pushButton_font_italic.setMinimumSize(QSize(30, 25))
        self.pushButton_font_italic.setMaximumSize(QSize(30, 25))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setItalic(True)
        self.pushButton_font_italic.setFont(font5)
        self.pushButton_font_italic.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_font_italic.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_font_italic, 0, 5, 1, 1)

        self.pushButton_font_underline = QPushButton(self.groupBox_label)
        self.pushButton_font_underline.setObjectName(u"pushButton_font_underline")
        self.pushButton_font_underline.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.pushButton_font_underline.sizePolicy().hasHeightForWidth())
        self.pushButton_font_underline.setSizePolicy(sizePolicy1)
        self.pushButton_font_underline.setMinimumSize(QSize(30, 25))
        self.pushButton_font_underline.setMaximumSize(QSize(30, 25))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setUnderline(True)
        self.pushButton_font_underline.setFont(font6)
        self.pushButton_font_underline.setFocusPolicy(Qt.ClickFocus)
        self.pushButton_font_underline.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_font_underline, 0, 6, 1, 1)


        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.groupBox_label)


        self.gridLayout_6.addWidget(self.widget_painting_tools, 2, 0, 1, 1)

        self.label_current_zoom = QLabel(self.centralwidget)
        self.label_current_zoom.setObjectName(u"label_current_zoom")
        sizePolicy1.setHeightForWidth(self.label_current_zoom.sizePolicy().hasHeightForWidth())
        self.label_current_zoom.setSizePolicy(sizePolicy1)
        self.label_current_zoom.setMinimumSize(QSize(160, 25))
        self.label_current_zoom.setMaximumSize(QSize(160, 25))
        self.label_current_zoom.setFont(font)

        self.gridLayout_6.addWidget(self.label_current_zoom, 0, 1, 1, 1)

        self.debug_btn = QPushButton(self.centralwidget)
        self.debug_btn.setObjectName(u"debug_btn")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.debug_btn.sizePolicy().hasHeightForWidth())
        self.debug_btn.setSizePolicy(sizePolicy3)
        self.debug_btn.setMinimumSize(QSize(150, 25))
        self.debug_btn.setMaximumSize(QSize(150, 25))
        self.debug_btn.setFont(font)
        self.debug_btn.setFocusPolicy(Qt.NoFocus)

        self.gridLayout_6.addWidget(self.debug_btn, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1425, 21))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_local_save = QMenu(self.menu_file)
        self.menu_local_save.setObjectName(u"menu_local_save")
        self.menu_open = QMenu(self.menu_file)
        self.menu_open.setObjectName(u"menu_open")
        self.menu_remote_save = QMenu(self.menu_file)
        self.menu_remote_save.setObjectName(u"menu_remote_save")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_additional = QMenu(self.menubar)
        self.menu_additional.setObjectName(u"menu_additional")
        self.menu_theme = QMenu(self.menu_additional)
        self.menu_theme.setObjectName(u"menu_theme")
        self.menu_dialog_windows = QMenu(self.menu_additional)
        self.menu_dialog_windows.setObjectName(u"menu_dialog_windows")
        self.menu_user_actions = QMenu(self.menubar)
        self.menu_user_actions.setObjectName(u"menu_user_actions")
        self.menu_user_actions.setEnabled(True)
        self.menu_edit = QMenu(self.menubar)
        self.menu_edit.setObjectName(u"menu_edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy4)
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_main = QToolBar(MainWindow)
        self.toolBar_main.setObjectName(u"toolBar_main")
        self.toolBar_main.setAllowedAreas(Qt.LeftToolBarArea|Qt.TopToolBarArea)
        self.toolBar_main.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_main)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_additional.menuAction())
        self.menubar.addAction(self.menu_user_actions.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_new_playbook)
        self.menu_file.addAction(self.menu_local_save.menuAction())
        self.menu_file.addAction(self.menu_remote_save.menuAction())
        self.menu_file.addAction(self.menu_open.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save_like_picture)
        self.menu_file.addAction(self.action_save_all_like_picture)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_close_app)
        self.menu_local_save.addAction(self.action_save_playbook_local)
        self.menu_local_save.addAction(self.action_save_playbook_local_as)
        self.menu_open.addAction(self.action_open_local_playbook)
        self.menu_open.addAction(self.action_open_remote_playbook)
        self.menu_remote_save.addAction(self.action_save_to_remote_server)
        self.menu_remote_save.addAction(self.action_save_to_remote_server_as)
        self.menu_help.addAction(self.action_about)
        self.menu_additional.addAction(self.action_presentation_mode)
        self.menu_additional.addAction(self.action_toolbar_visible)
        self.menu_additional.addAction(self.menu_dialog_windows.menuAction())
        self.menu_additional.addSeparator()
        self.menu_additional.addAction(self.menu_theme.menuAction())
        self.menu_theme.addAction(self.action_light_theme)
        self.menu_theme.addAction(self.action_dark_theme)
        self.menu_dialog_windows.addAction(self.action_show_remove_scheme_dialog)
        self.menu_dialog_windows.addAction(self.action_show_close_app_dialog)
        self.menu_dialog_windows.addAction(self.action_show_save_changed_playbook_dialog)
        self.menu_user_actions.addAction(self.action_user_login)
        self.menu_user_actions.addSeparator()
        self.menu_user_actions.addAction(self.action_user_logout)
        self.menu_edit.addAction(self.action_undo)
        self.menu_edit.addAction(self.action_redo)
        self.toolBar_main.addAction(self.action_new_playbook)
        self.toolBar_main.addSeparator()
        self.toolBar_main.addAction(self.action_open_local_playbook)
        self.toolBar_main.addAction(self.action_save_playbook_local)
        self.toolBar_main.addAction(self.action_save_playbook_local_as)
        self.toolBar_main.addSeparator()
        self.toolBar_main.addAction(self.action_open_remote_playbook)
        self.toolBar_main.addAction(self.action_save_to_remote_server)
        self.toolBar_main.addSeparator()
        self.toolBar_main.addAction(self.action_save_like_picture)
        self.toolBar_main.addAction(self.action_save_all_like_picture)
        self.toolBar_main.addSeparator()
        self.toolBar_main.addAction(self.action_presentation_mode)

        self.retranslateUi(MainWindow)

        self.comboBox_line_thickness.setCurrentIndex(0)
        self.comboBox_font_size.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PlayCreator", None))
        self.action_save_like_picture.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043a\u0430\u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435", None))
#if QT_CONFIG(tooltip)
        self.action_save_like_picture.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + Shift + S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save_like_picture.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043a\u0430\u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 (Ctrl + Shift + S)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_save_like_picture.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
#if QT_CONFIG(statustip)
        self.action_about.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
#endif // QT_CONFIG(statustip)
        self.action_presentation_mode.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0436\u0438\u043c \u043f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u0438", None))
#if QT_CONFIG(statustip)
        self.action_presentation_mode.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0436\u0438\u043c \u043f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u0438", None))
#endif // QT_CONFIG(statustip)
        self.action_QB_Wrist.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0434\u0435\u043b\u0430\u0442\u044c \"QB Wrist\"", None))
        self.action_light_theme.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0432\u0435\u0442\u043b\u0430\u044f", None))
#if QT_CONFIG(statustip)
        self.action_light_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u0432\u0435\u0442\u043b\u0430\u044f \u0442\u0435\u043c\u0430", None))
#endif // QT_CONFIG(statustip)
        self.action_dark_theme.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0451\u043c\u043d\u0430\u044f", None))
#if QT_CONFIG(statustip)
        self.action_dark_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u0451\u043c\u043d\u0430\u044f \u0442\u0435\u043c\u0430", None))
#endif // QT_CONFIG(statustip)
        self.action_save_all_like_picture.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0432\u0441\u0451 \u043a\u0430\u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f", None))
#if QT_CONFIG(tooltip)
        self.action_save_all_like_picture.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + Shift + A", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save_all_like_picture.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0432\u0441\u0451 \u043a\u0430\u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f (Ctrl + Shift + A)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_save_all_like_picture.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_playbook_local.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
#if QT_CONFIG(tooltip)
        self.action_save_playbook_local.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save_playbook_local.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435 (Ctrl + S)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_save_playbook_local.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_new_playbook.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u0432\u044b\u0439 \u043f\u043b\u0435\u0439\u0431\u0443\u043a", None))
#if QT_CONFIG(tooltip)
        self.action_new_playbook.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + N", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_new_playbook.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u0432\u044b\u0439 \u043f\u043b\u0435\u0439\u0431\u0443\u043a (Ctrl + N)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_new_playbook.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_user_login.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0445\u043e\u0434", None))
#if QT_CONFIG(statustip)
        self.action_user_login.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u0445\u043e\u0434", None))
#endif // QT_CONFIG(statustip)
        self.action_user_logout.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
#if QT_CONFIG(statustip)
        self.action_user_logout.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
#endif // QT_CONFIG(statustip)
        self.action_open_local_playbook.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u0441 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0430", None))
#if QT_CONFIG(tooltip)
        self.action_open_local_playbook.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + O", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_open_local_playbook.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u0441 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0430 (Ctrl + O)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_open_local_playbook.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_close_app.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435", None))
#if QT_CONFIG(statustip)
        self.action_close_app.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435", None))
#endif // QT_CONFIG(statustip)
        self.action_open_remote_playbook.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u0441 \u0441\u0435\u0440\u0432\u0435\u0440\u0430", None))
#if QT_CONFIG(statustip)
        self.action_open_remote_playbook.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u0441 \u0441\u0435\u0440\u0432\u0435\u0440\u0430", None))
#endif // QT_CONFIG(statustip)
        self.action_toolbar_visible.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0430\u043d\u0435\u043b\u044c \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u043e\u0432", None))
#if QT_CONFIG(statustip)
        self.action_toolbar_visible.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c / \u0443\u0431\u0440\u0430\u0442\u044c \u043f\u0430\u043d\u0435\u043b\u044c \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u043e\u0432", None))
#endif // QT_CONFIG(statustip)
        self.action_save_playbook_local_as.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043a\u0430\u043a...", None))
        self.action_save_playbook_local_as.setIconText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435 \u043a\u0430\u043a...", None))
#if QT_CONFIG(tooltip)
        self.action_save_playbook_local_as.setToolTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435 \u043a\u0430\u043a...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save_playbook_local_as.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435 \u043a\u0430\u043a...", None))
#endif // QT_CONFIG(statustip)
        self.action_show_remove_scheme_dialog.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u0441\u0445\u0435\u043c\u044b", None))
#if QT_CONFIG(statustip)
        self.action_show_remove_scheme_dialog.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043e\u043a\u043d\u043e \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u0441\u0445\u0435\u043c\u044b", None))
#endif // QT_CONFIG(statustip)
        self.action_show_close_app_dialog.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f", None))
#if QT_CONFIG(statustip)
        self.action_show_close_app_dialog.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043e\u043a\u043d\u043e \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.action_redo.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c", None))
#if QT_CONFIG(statustip)
        self.action_redo.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_redo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_undo.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c", None))
#if QT_CONFIG(statustip)
        self.action_undo.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_undo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_to_remote_server_as.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043a\u0430\u043a...", None))
        self.action_save_to_remote_server.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
#if QT_CONFIG(statustip)
        self.action_save_to_remote_server.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u043d\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435", None))
#endif // QT_CONFIG(statustip)
        self.action_show_save_changed_playbook_dialog.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0438\u0437\u043c\u0435\u043d\u0451\u043d\u043d\u043e\u0433\u043e \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430", None))
#if QT_CONFIG(statustip)
        self.action_show_save_changed_playbook_dialog.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043e\u043a\u043d\u043e \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0438\u0437\u043c\u0435\u043d\u0451\u043d\u043d\u043e\u0433\u043e \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430", None))
#endif // QT_CONFIG(statustip)
        self.groupBox_team_playbook_settings.setTitle("")
        self.label_place_players.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443:", None))
        self.comboBox_team_type.setItemText(0, QCoreApplication.translate("MainWindow", u"\u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
        self.comboBox_team_type.setItemText(1, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043a\u0438\u043a\u043e\u0444\u0430", None))
        self.comboBox_team_type.setItemText(2, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043f\u0430\u043d\u0442\u0430", None))
        self.comboBox_team_type.setItemText(3, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043f\u043e \u0432\u043e\u0440\u043e\u0442\u0430\u043c", None))

#if QT_CONFIG(statustip)
        self.comboBox_team_type.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0442\u0438\u043f\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u044b", None))
#endif // QT_CONFIG(statustip)
        self.label_yards.setText(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b:", None))
#if QT_CONFIG(statustip)
        self.lineEdit_yards.setStatusTip(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_yards.setInputMask("")
        self.lineEdit_yards.setText(QCoreApplication.translate("MainWindow", u"50", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_second_team.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0432\u0442\u043e\u0440\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_second_team.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043f\u0440\u043e\u0442\u0438\u0432\u043d\u0438\u043a\u043e\u0432", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_first_team.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043f\u0435\u0440\u0432\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_first_team.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c", None))
#if QT_CONFIG(statustip)
        self.pushButton_remove_second_team.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0442\u043e\u0440\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_second_team.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u0440\u043e\u0442\u0438\u0432\u043d\u0438\u043a\u043e\u0432", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_additional_off_player.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_additional_off_player.setText(QCoreApplication.translate("MainWindow", u"+1", None))
#if QT_CONFIG(statustip)
        self.pushButton_del_additional_off_player.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_del_additional_off_player.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.comboBox_second_players_symbol.setItemText(0, QCoreApplication.translate("MainWindow", u"T, E...", None))
        self.comboBox_second_players_symbol.setItemText(1, QCoreApplication.translate("MainWindow", u"X", None))
        self.comboBox_second_players_symbol.setItemText(2, QCoreApplication.translate("MainWindow", u"\u25bc", None))
        self.comboBox_second_players_symbol.setItemText(3, QCoreApplication.translate("MainWindow", u"\u25b2", None))

#if QT_CONFIG(statustip)
        self.comboBox_second_players_symbol.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0438\u0433\u0440\u043e\u043a\u043e\u0432 \u0437\u0430\u0449\u0438\u0442\u044b \u043d\u0430 \u0441\u0445\u0435\u043c\u0435", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.pushButton_remove_all_players.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445 \u0438\u0433\u0440\u043e\u043a\u043e\u0432", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_all_players.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445", None))
#if QT_CONFIG(statustip)
        self.label_playbook_name.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043b\u0435\u0439\u0431\u0443\u043a\u0430", None))
#endif // QT_CONFIG(statustip)
        self.label_playbook_name.setText("")
#if QT_CONFIG(statustip)
        self.pushButton_edit_playbook.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_edit_playbook.setText("")
#if QT_CONFIG(statustip)
        self.pushButton_edit_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_edit_scheme.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_scheme.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(statustip)
        self.pushButton_move_up_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u0432\u0435\u0440\u0445", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_move_up_scheme.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
#if QT_CONFIG(statustip)
        self.pushButton_move_down_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u043d\u0438\u0437", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_move_down_scheme.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
#if QT_CONFIG(statustip)
        self.pushButton_remove_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_scheme.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_move_erase.setTitle("")
#if QT_CONFIG(tooltip)
        self.pushButton_move.setToolTip(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_move.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u0442\u0430\u0441\u043a\u0438\u0432\u0430\u043d\u0438\u0435 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u043e\u0432 (S)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_move.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_move.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_erase.setToolTip(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_erase.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u043e\u0442\u0434\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u0430 (D)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_erase.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_erase.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_colors.setTitle("")
#if QT_CONFIG(statustip)
        self.pushButton_color_current.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0446\u0432\u0435\u0442 / \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u0441\u0432\u043e\u0439 \u0446\u0432\u0435\u0442", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_color_current.setText("")
        self.pushButton_color_10.setText("")
        self.pushButton_color_9.setText("")
        self.pushButton_color_4.setText("")
        self.pushButton_color_6.setText("")
        self.pushButton_color_7.setText("")
        self.pushButton_color_1.setText("")
        self.pushButton_color_8.setText("")
        self.pushButton_color_2.setText("")
        self.pushButton_color_3.setText("")
        self.pushButton_color_0.setText("")
        self.pushButton_color_5.setText("")
        self.pushButton_color_11.setText("")
        self.groupBox_painting.setTitle("")
#if QT_CONFIG(tooltip)
        self.pushButton_remove_actions.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + Q", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_remove_actions.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0439 \u0438\u0433\u0440\u043e\u043a\u043e\u0432 (Ctrl + Q)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_actions.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_remove_actions.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_route.setToolTip(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_route.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0440\u0448\u0440\u0443\u0442\u0430 (Q)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_route.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_route.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_block.setToolTip(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_block.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u0431\u043b\u043e\u043a\u0430 (W)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_block.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_block.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_motion.setToolTip(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_motion.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0443\u0448\u0435\u043d\u0430 (E)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_motion.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_motion.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_remove_pencil.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + F", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_remove_pencil.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u0430 (Ctrl + F)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_pencil.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_remove_pencil.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_rectangle.setToolTip(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_rectangle.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u044f\u043c\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 (R)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_rectangle.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_rectangle.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_remove_figures.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_remove_figures.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u0444\u0438\u0433\u0443\u0440 (Ctrl + R)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_figures.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_remove_figures.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_ellipse.setToolTip(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_ellipse.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u044d\u043b\u043b\u0438\u043f\u0441\u0430 (T)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_ellipse.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_ellipse.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_pencil.setToolTip(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_pencil.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u043e\u043c (F)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_pencil.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_pencil.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.comboBox_line_thickness.setItemText(0, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_line_thickness.setItemText(1, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_line_thickness.setItemText(2, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_line_thickness.setItemText(3, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_line_thickness.setItemText(4, QCoreApplication.translate("MainWindow", u"6", None))

#if QT_CONFIG(statustip)
        self.comboBox_line_thickness.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u043e\u043b\u0449\u0438\u043d\u0430 \u043b\u0438\u043d\u0438\u0439", None))
#endif // QT_CONFIG(statustip)
        self.groupBox_label.setTitle("")
#if QT_CONFIG(tooltip)
        self.pushButton_label.setToolTip(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_label.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u0435 \u043d\u0430\u0434\u043f\u0438\u0441\u0435\u0439 (C)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_label.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_label.setShortcut(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_remove_labels.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + C", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_remove_labels.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u043d\u0430\u0434\u043f\u0438\u0441\u0435\u0439 (Ctrl + C)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_remove_labels.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_remove_labels.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(statustip)
        self.comboBox_font_type.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0448\u0440\u0438\u0444\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
        self.comboBox_font_size.setItemText(0, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_font_size.setItemText(1, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_font_size.setItemText(2, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_font_size.setItemText(3, QCoreApplication.translate("MainWindow", u"11", None))
        self.comboBox_font_size.setItemText(4, QCoreApplication.translate("MainWindow", u"12", None))
        self.comboBox_font_size.setItemText(5, QCoreApplication.translate("MainWindow", u"14", None))
        self.comboBox_font_size.setItemText(6, QCoreApplication.translate("MainWindow", u"16", None))
        self.comboBox_font_size.setItemText(7, QCoreApplication.translate("MainWindow", u"18", None))
        self.comboBox_font_size.setItemText(8, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_font_size.setItemText(9, QCoreApplication.translate("MainWindow", u"22", None))
        self.comboBox_font_size.setItemText(10, QCoreApplication.translate("MainWindow", u"24", None))
        self.comboBox_font_size.setItemText(11, QCoreApplication.translate("MainWindow", u"26", None))
        self.comboBox_font_size.setItemText(12, QCoreApplication.translate("MainWindow", u"28", None))
        self.comboBox_font_size.setItemText(13, QCoreApplication.translate("MainWindow", u"36", None))

#if QT_CONFIG(statustip)
        self.comboBox_font_size.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0440 \u0448\u0440\u0438\u0444\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton_font_bold.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_font_bold.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0416\u0438\u0440\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442 (Ctrl+B)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_font_bold.setText(QCoreApplication.translate("MainWindow", u"\u0416", None))
#if QT_CONFIG(shortcut)
        self.pushButton_font_bold.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_font_italic.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_font_italic.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u0440\u0441\u0438\u0432 (Ctrl+I)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_font_italic.setText(QCoreApplication.translate("MainWindow", u"\u041a", None))
#if QT_CONFIG(shortcut)
        self.pushButton_font_italic.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_font_underline.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_font_underline.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0447\u0451\u0440\u043a\u0438\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u043a\u0441\u0442\u0430 (Ctrl+U)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_font_underline.setText(QCoreApplication.translate("MainWindow", u"\u0427", None))
#if QT_CONFIG(shortcut)
        self.pushButton_font_underline.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.label_current_zoom.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0438\u0431\u043b\u0438\u0436\u0435\u043d\u0438\u0435: 0%", None))
        self.debug_btn.setText(QCoreApplication.translate("MainWindow", u"debug_btn", None))
        self.menu_file.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0430\u0438\u043b", None))
        self.menu_local_save.setTitle(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435", None))
        self.menu_open.setTitle(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c", None))
        self.menu_remote_save.setTitle(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u043b\u0435\u0439\u0431\u0443\u043a \u043d\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043c\u043e\u0449\u044c", None))
        self.menu_additional.setTitle(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e", None))
#if QT_CONFIG(statustip)
        self.menu_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0442\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.menu_theme.setTitle(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043c\u0430", None))
        self.menu_dialog_windows.setTitle(QCoreApplication.translate("MainWindow", u"\u0414\u0438\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0435 \u043e\u043a\u043d\u0430", None))
        self.menu_user_actions.setTitle(QCoreApplication.translate("MainWindow", u"\u0423\u0447\u0451\u0442\u043d\u0430\u044f \u0437\u0430\u043f\u0438\u0441\u044c", None))
        self.menu_edit.setTitle(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435", None))
        self.toolBar_main.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

